import json
h = open('page.html').read()
logo = open('logo.b64').read().strip()
assert len(logo) > 1000, "logo missing"
h = h.replace('%%LOGO%%', logo)
P = open('play.html', encoding='utf-8').read()
MANIFEST_JSON = '{"name": "Vibe Hunt - J-seyVibeCat", "short_name": "Vibe Hunt", "start_url": "/play", "scope": "/play", "display": "standalone", "background_color": "#050816", "theme_color": "#050816", "icons": [{"src": "/og.png", "sizes": "320x320", "type": "image/png", "purpose": "any"}]}'
SW_JS = "self.addEventListener('install',function(e){self.skipWaiting()});self.addEventListener('activate',function(e){e.waitUntil(self.clients.claim())});self.addEventListener('fetch',function(e){});"
js = (
    'const html = ' + json.dumps(h) + ';\n'
    'const playHtml = ' + json.dumps(P) + ';\n'
    'const logoB64 = ' + json.dumps(logo) + ';\n'
    'function b64ToBytes(b64){const bin=atob(b64);const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return bytes}\n\n'
    'const JVC_CA="0xA79b75CFed3D0b1de47A313cfE18b2322c51e301";\n'
    'const JVC_CURVE="0xA7FcB6e71A1AECd9686DC66248C4173dEfe306bb";\n'
    'async function jvTrack(request,env,url,ctx){\n const p=url.pathname,ck=request.headers.get(\'cookie\')||\'\';\n if(p===\'/jvme\')return new Response(\'You are excluded on this browser.\',{headers:{\'set-cookie\':\'jvme=1; Max-Age=315360000; Path=/; Secure; SameSite=Lax\',\'content-type\':\'text/plain\'}});\n if(p===\'/api/visits\'){\n  if(url.searchParams.get(\'k\')!==\'40eaea045b57c20c\')return new Response(\'Not found\',{status:404});\n  try{\n   const q=async(s)=>(await env.DB.prepare(s).all()).results;\n   const now=Math.floor(Date.now()/1000);\n   const o={total:(await q(\'SELECT COUNT(*) c, COUNT(DISTINCT vid) u FROM visits\'))[0],last24h:(await q(\'SELECT COUNT(*) c, COUNT(DISTINCT vid) u FROM visits WHERE ts>\'+(now-86400)))[0],days:await q("SELECT date(ts,\'unixepoch\') d, COUNT(*) c, COUNT(DISTINCT vid) u FROM visits GROUP BY d ORDER BY d DESC LIMIT 14"),countries:await q(\'SELECT cc, COUNT(DISTINCT vid) u FROM visits GROUP BY cc ORDER BY u DESC LIMIT 10\'),referrers:await q("SELECT ref, COUNT(*) c FROM visits WHERE ref!=\'\' GROUP BY ref ORDER BY c DESC LIMIT 10"),paths:await q(\'SELECT path, COUNT(*) c FROM visits GROUP BY path\'),recent:await q("SELECT datetime(ts,\'unixepoch\') t, path, cc, ref FROM visits ORDER BY ts DESC LIMIT 15")};\n   return new Response(JSON.stringify(o,null,1),{headers:{\'content-type\':\'application/json\',\'cache-control\':\'no-store\'}});\n  }catch(e){return new Response(\'{"total":{"c":0,"u":0}}\',{headers:{\'content-type\':\'application/json\'}})}\n }\n if(request.method===\'GET\'&&(p===\'/\'||p===\'/play\')&&!/(^|; )jvme=1/.test(ck)){\n  const ua=request.headers.get(\'user-agent\')||\'\';\n  if(!/bot|crawl|spider|preview|facebookexternalhit|slurp|curl|wget|python/i.test(ua)){\n   ctx.waitUntil((async()=>{try{\n    const ip=request.headers.get(\'cf-connecting-ip\')||\'\';\n    const h=await crypto.subtle.digest(\'SHA-256\',new TextEncoder().encode(ip+ua));\n    const vid=[...new Uint8Array(h)].slice(0,6).map(x=>x.toString(16).padStart(2,\'0\')).join(\'\');\n    let ref=\'\';try{ref=new URL(request.headers.get(\'referer\')||\'\').hostname}catch(e){}\n    if(ref===url.hostname)ref=\'\';\n    await env.DB.prepare(\'CREATE TABLE IF NOT EXISTS visits(ts INTEGER,path TEXT,vid TEXT,cc TEXT,ref TEXT)\').run();\n    await env.DB.prepare(\'INSERT INTO visits VALUES(?,?,?,?,?)\').bind(Math.floor(Date.now()/1000),p,vid,(request.cf&&request.cf.country)||\'\',ref).run();\n   }catch(e){}})());\n  }\n }\n return null;\n}\n'
    "async function jvcPc2(env,sample){\n const R='https://rpc.testnet.chain.robinhood.com/rpc',PM='0x8366a39CC670B4001A1121B8F6A443A643e40951';\n const T=['0x40e9cecb9f5f1f1c5b9c97dec2917b7ee92e57ba5563708daca94dd84ad7112f','0x09ed977e19d6fcabfff7e191911ba5da9272f6c0dde188350ef82a934f95559b'];\n const call=async(m,p)=>{const r=await fetch(R,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:m,params:p})});return (await r.json()).result};\n const px=x=>{const s=Number(BigInt('0x'+x.data.slice(2).slice(128,192)))/2**96;return s>0?1/(s*s):0};\n if(sample){\n  try{\n   await env.DB.prepare('DELETE FROM prices WHERE p<1e-10').run();\n   const cnt=(await env.DB.prepare('SELECT COUNT(*) c FROM prices').first()).c;\n   if(cnt<5){\n    const all=await call('eth_getLogs',[{address:PM,topics:T,fromBlock:'0x'+(125797411).toString(16),toBlock:'latest'}])||[];\n    const st=[];const bc={};\n    for(const x of all.slice(-30)){\n     if(!bc[x.blockNumber]){const b=await call('eth_getBlockByNumber',[x.blockNumber,false]);bc[x.blockNumber]=b?parseInt(b.timestamp,16):0}\n     const p=px(x);if(bc[x.blockNumber]&&p>0&&isFinite(p))st.push(env.DB.prepare('INSERT OR REPLACE INTO prices(ts,p) VALUES(?,?)').bind(bc[x.blockNumber],p));\n    }\n    if(st.length)await env.DB.batch(st);\n   }\n   const bn=parseInt(await call('eth_blockNumber',[]),16);\n   let lg=[];\n   for(const sp of [20000,500000,3000000]){\n    lg=await call('eth_getLogs',[{address:PM,topics:T,fromBlock:'0x'+(bn-sp).toString(16),toBlock:'latest'}])||[];\n    if(lg.length)break;\n   }\n   if(lg.length){const p=px(lg[lg.length-1]);if(p>0&&isFinite(p))await env.DB.prepare('INSERT OR REPLACE INTO prices(ts,p) VALUES(?,?)').bind(Math.floor(Date.now()/1000),p).run();}\n  }catch(e){}\n  return new Response('ok');\n }\n const H={'content-type':'application/json','cache-control':'no-store','access-control-allow-origin':'*'};\n const last=await env.DB.prepare('SELECT ts,p FROM prices WHERE p>1e-10 ORDER BY ts DESC LIMIT 1').first();\n if(!last)return new Response(JSON.stringify({p:0,ch:0,h:0}),{headers:H});\n let old=await env.DB.prepare('SELECT ts,p FROM prices WHERE p>1e-10 AND ts<=? ORDER BY ts DESC LIMIT 1').bind(last.ts-86400).first();\n if(!old)old=await env.DB.prepare('SELECT ts,p FROM prices WHERE p>1e-10 ORDER BY ts ASC LIMIT 1').first();\n return new Response(JSON.stringify({p:last.p,ch:(last.p/old.p-1)*100,h:(last.ts-old.ts)/3600}),{headers:H});\n}\n"
    'async function jvcPc(env){\n'
    '  const H={"content-type":"application/json","cache-control":"no-store","access-control-allow-origin":"*"};\n'
    '  try{\n'
    '    const now=Math.floor(Date.now()/1000);\n'
    '    const last=await env.DB.prepare("SELECT ts,p FROM prices ORDER BY ts DESC LIMIT 1").first();\n'
    '    let cur=last?last.p:null;\n'
    '    if(!last||now-last.ts>=270){\n'
    '      try{\n'
    '        const B="https://explorer.testnet.chain.robinhood.com/api/v2/";\n'
    '        const J=(u)=>fetch(u).then((r)=>r.json());\n'
    '        const [t,a,tb]=await Promise.all([J(B+"tokens/"+JVC_CA),J(B+"addresses/"+JVC_CURVE),J(B+"addresses/"+JVC_CURVE+"/token-balances")]);\n'
    '        const arr=Array.isArray(tb)?tb:(tb.items||[]);\n'
    '        let cb=0n;\n'
    '        for(const x of arr){const tk=x.token||{};const hh=(tk.address_hash||tk.address||"").toLowerCase();if(hh===JVC_CA.toLowerCase())cb=BigInt(x.value||"0")}\n'
    '        const sold=BigInt(t.total_supply)-cb;\n'
    '        if(sold>0n){\n'
    '          const p=Number(BigInt(a.coin_balance||"0")*(10n**18n)/sold)/1e18;\n'
    '          if(p>0){cur=p;await env.DB.prepare("INSERT OR REPLACE INTO prices(ts,p) VALUES(?,?)").bind(now,p).run();await env.DB.prepare("DELETE FROM prices WHERE ts<?").bind(now-259200).run()}\n'
    '        }\n'
    '      }catch(e){}\n'
    '    }\n'
    '    let ref=await env.DB.prepare("SELECT ts,p FROM prices WHERE ts<=? ORDER BY ts DESC LIMIT 1").bind(now-86400).first();\n'
    '    if(!ref)ref=await env.DB.prepare("SELECT ts,p FROM prices ORDER BY ts ASC LIMIT 1").first();\n'
    '    let ch=null,hrs=0;\n'
    '    if(cur&&ref&&ref.p>0&&now-ref.ts>=3600){ch=(cur-ref.p)/ref.p*100;hrs=(now-ref.ts)/3600}\n'
    '    return new Response(JSON.stringify({p:cur,ch:ch,h:hrs}),{headers:H});\n'
    '  }catch(e){return new Response(JSON.stringify({p:null,ch:null,h:0}),{headers:{"content-type":"application/json","access-control-allow-origin":"*"}})}\n'
    '}\n'
    'export default {\n'
    '  async scheduled(event, env, ctx) { ctx.waitUntil(jvcPc2(env,true)); },\n'
    '  async fetch(request, env, ctx) {\n'
    '    const url = new URL(request.url);\n'
    '    if (url.pathname === "/.well-known/walletconnect.txt") return new Response("4618e5ec60732bfdde596851c16e3b57", { headers: { "content-type": "text/plain" } });\n'
    '    { const __t=await jvTrack(request,env,url,ctx); if(__t){ const __h=new Headers(__t.headers); __h.set("access-control-allow-origin","*"); return new Response(__t.body,{status:__t.status,headers:__h}); } }\n'
    '    if (url.pathname === "/api/pc") return jvcPc2(env,false);\n'
    '    if (url.pathname === "/og.png") {\n'
    '      return new Response(b64ToBytes(logoB64), { headers: { "content-type": "image/png", "cache-control": "public, max-age=3600" } });\n'
    '    }\n'
    'if (url.pathname.startsWith("/images/")) {\n'
    '  const key = url.pathname.slice("/images/".length);\n'
    '  if (!env.IMAGES) return new Response("Not found", { status: 404 });\n'
    '  const obj = await env.IMAGES.get(key);\n'
    '  if (!obj) return new Response("Not found", { status: 404 });\n'
    '  return new Response(obj.body, { headers: { "content-type": "image/jpeg", "cache-control": "max-age=86400" } });\n'
    '}\n'
    '    if (url.pathname === "/play" || url.pathname === "/play/") return new Response(playHtml, { headers: { "content-type": "text/html;charset=UTF-8", "cache-control": "no-cache" } });\n'
    '    if (url.pathname === "/manifest.webmanifest") return new Response(' + json.dumps(MANIFEST_JSON) + ', { headers: { "content-type": "application/manifest+json", "cache-control": "no-cache" } });\n'
    '    if (url.pathname === "/sw.js") return new Response(' + json.dumps(SW_JS) + ', { headers: { "content-type": "application/javascript", "cache-control": "no-cache" } });\n'
    '    return new Response(html, { headers: { "content-type": "text/html;charset=UTF-8", "cache-control": "no-cache" } });\n'
    '  }\n'
    '};\n'
)
open('worker.js', 'w').write(js)
print('built', len(js), 'bytes')
